# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 63a671753488793f585b70dd3bb1dcc6c5c4718ced9e00b3271dbcc25fe00aaf27709d3fdfc7080a51001a31434012c9e31f3b7fab6fc4a2523f549f5c77745c

test:
  secret_key_base: cedf4d66da131bc3372059e1f0a5989647d56e2034c2fdedc58a89bf1b10cd0a8c402cd9dcbd32663b2dba23841c7fd303d705310d8968da0c36107b8ad495b3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
